// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDcFbK3XBzFQ5CofTNWtUgO_7XSn_RPa7g',
    appId: '1:994229341685:web:10a64ae6e032129914e4bc',
    messagingSenderId: '994229341685',
    projectId: 'theraphy-71e99',
    authDomain: 'theraphy-71e99.firebaseapp.com',
    storageBucket: 'theraphy-71e99.appspot.com',
    measurementId: 'G-8CW4K0RL3P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAnB5ALXeugA9h5W8LnoeWqbofJF9kewmw',
    appId: '1:994229341685:android:a0c6445ed4ce930614e4bc',
    messagingSenderId: '994229341685',
    projectId: 'theraphy-71e99',
    storageBucket: 'theraphy-71e99.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB3TTAiEXI5G6EyWLfb7rDmOG5ACZa1yzU',
    appId: '1:994229341685:ios:9e01c80164221d0f14e4bc',
    messagingSenderId: '994229341685',
    projectId: 'theraphy-71e99',
    storageBucket: 'theraphy-71e99.appspot.com',
    iosBundleId: 'com.example.mobileAppTheraphy',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB3TTAiEXI5G6EyWLfb7rDmOG5ACZa1yzU',
    appId: '1:994229341685:ios:87763039e5c825ab14e4bc',
    messagingSenderId: '994229341685',
    projectId: 'theraphy-71e99',
    storageBucket: 'theraphy-71e99.appspot.com',
    iosBundleId: 'com.example.mobileAppTheraphy.RunnerTests',
  );
}
